### PR TITLE
fix issue #235

### LINKED ISSUE #235: bug: TypeError: Cannot convert object to primitive value
**What?**

The string validator is in someway evaluating the objects coming as params and it breaks if it has native prototype references (e.g. toString, toJSON)

**How to reproduce it?**

```js
const Validator = require("fastest-validator");
const v = new Validator();
const schema = {    name: { type: "string" },};
const check = v.compile(schema);

console.log(check({ name: "test"})); // it works, and passes
console.log(check({ name: { "abc": 1 }})); // it works, and rejects
console.log(check({ name: { "toString": 1 }})); // it fails - TypeError: Cannot convert object to primitive value
```

**Environment:**

$ node --version
v12.16.1
macOS Catalina 10.15.16
fastest-validator version: 1.11.0

**Comments:**
I didn't inspect the code deeply, but if you have any suggestions about how to solve it, I will be glad to help!

### PR DESCRIPTION
**Pull request by erfanium**
fixes #235

### CODE REVIEW

File: lib/helpers/replace.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+function convertible(value) {
+	if (value === undefined) return "";
+	if (value === null) return "";
+	if (typeof value.toString === "function") return value;
+	return typeof value;
```
Comment (icebob) [inline lib/helpers/replace.js:5]: Why return the typeof and not the value?

Comment (erfanium) [reply lib/helpers/replace.js:5]: Because value doesn't implement `toString` method and can't be used by `String.prototype.replace`

Comment (erfanium) [reply lib/helpers/replace.js:5]: for reproduce:
```js
const o1 = { a: 5 }
const o2 = { toString: 5 }
const s = "abc"
s.replace("b", o1) // worked
s.replace("b", o2) // fail

```

**Review by icebob — APPROVED** [review]
